import sys

from .adapters.enterprise_adapter import EnterpriseActionTool
from .adapters.mcp_adapter import MCPServerAdapter
from .adapters.zapier_adapter import ZapierActionTool
from .aws import (
    BedrockInvokeAgentTool,
    BedrockKBRetrieverTool,
    S3ReaderTool,
    S3WriterTool,
)
from .tools import (
    AIMindTool,
    ApifyActorsTool,
    ArxivPaperTool,
    BraveSearchTool,
    BrightDataDatasetTool,
    BrightDataSearchTool,
    BrightDataWebUnlockerTool,
    BrowserbaseLoadTool,
    BrowserUseTool,
    CodeDocsSearchTool,
    CodeInterpreterTool,
    ComposioTool,
    CouchbaseFTSVectorSearchTool,
    CrewaiEnterpriseTools,
    CSVSearchTool,
    DallETool,
    DatabricksQueryTool,
    DirectoryReadTool,
    DirectorySearchTool,
    DOCXSearchTool,
    EXASearchTool,
    FileCompressorTool,
    FileReadTool,
    FileWriterTool,
    FirecrawlCrawlWebsiteTool,
    FirecrawlScrapeWebsiteTool,
    FirecrawlSearchTool,
    GithubSearchTool,
    HyperbrowserLoadTool,
    JSONSearchTool,
    LinkupSearchTool,
    LlamaIndexTool,
    MDXSearchTool,
    MongoDBVectorSearchConfig,
    MongoDBVectorSearchTool,
    MultiOnTool,
    MySQLSearchTool,
    NL2SQLTool,
    OxylabsAmazonProductScraperTool,
    OxylabsAmazonSearchScraperTool,
    OxylabsGoogleSearchScraperTool,
    OxylabsUniversalScraperTool,
    PatronusEvalTool,
    PatronusLocalEvaluatorTool,
    PatronusPredefinedCriteriaEvalTool,
    PDFSearchTool,
    PGSearchTool,
    QdrantVectorSearchTool,
    RagTool,
    ScrapeElementFromWebsiteTool,
    ScrapegraphScrapeTool,
    ScrapegraphScrapeToolSchema,
    ScrapeWebsiteTool,
    ScrapflyScrapeWebsiteTool,
    SeleniumScrapingTool,
    SerpApiGoogleSearchTool,
    SerpApiGoogleShoppingTool,
    SerperDevTool,
    SerperScrapeWebsiteTool,
    SerplyJobSearchTool,
    SerplyNewsSearchTool,
    SerplyScholarSearchTool,
    SerplyWebpageToMarkdownTool,
    SerplyWebSearchTool,
    SingleStoreSearchTool,
    SnowflakeConfig,
    SnowflakeSearchTool,
    SpiderTool,
    StagehandTool,
    TavilyExtractorTool,
    TavilySearchTool,
    TXTSearchTool,
    VisionTool,
    WeaviateVectorSearchTool,
    WebsiteSearchTool,
    XMLSearchTool,
    YoutubeChannelSearchTool,
    YoutubeVideoSearchTool,
    ZapierActionTools,
)

# Proper error handling for the 'browser-use' extra when using Python < 3.11
if sys.version_info < (3, 11):
    raise RuntimeError("The 'browser-use' extra requires Python >= 3.11")
